[package]
name = "mascot-rs"
version = "0.1.0"
edition = "2021"
authors = ["Luca Cappelletti <cappelletti.luca94@gmail.com>"]
description = "A library to read mascot spectra files"
homepage = "https://github.com/LucaCappelletti94/mascot-rs"
repository = "https://github.com/LucaCappelletti94/mascot-rs"
readme = "README.md"
license = "MIT"
keywords = ["mascot", "format", "spectrography"]
categories = [
    "science",
]

[dev-dependencies]
serde_json = "1.0.105"